### ISSUE TITLE
Short cut to close the editor

### ISSUE THREAD

**Issue by JoePython1** [fredoverflow/clopad#1]
Is there keyboard shortcut( say Ctrl-q) to close the editor?

**Comment by fredoverflow** [comment]
Does Alt+F4 work for you?

**Comment by JoePython1** [comment]
No it doesn't either. btw, I use the xmonad window manager.

**Comment by JoePython1** [comment]
I can use the Mod-shift-c in xmonad to close the windows.
Thank you.
