### ISSUE TITLE
Usage of Clopad?

### ISSUE THREAD

**Issue by ILoveHubGit** [fredoverflow/clopad#3]
Hi, I just saw some videos of you on youtube where you make use of Clopad. In there you showed, but did not explain, that you can evaluate a single function in Clopad. I like the interface very much, especially the separation of the code and the output.

How can I evaluate a single function? When I start Clopad I can only use F5 to run the complete program.

Thanks in advance

**Comment by fredoverflow** [comment]
When you start Clopad for the first time, you should see example code with the following help on top:

    ;; F1  show source or doc-string (same as right-click)
    ;; F5  evaluate    whole program
    ;; F11 macroexpand top-level form (CTRL also expands nested macros)
    ;; F12 evaluate    top-level form
    ;; SHIFT activates pretty-printing

I guess you accidentally deleted that comment?

If you want to call a function `foo` with the arguments `42` and `"hello"`, just write

    (foo 42 "hello")

and press F12. (The cursor has to be somewhere between "before the opening parenthesis" and "after the closing parenthesis" for the system to recognize that call to foo as the current top-level form.)

P.S. I made 8 commits this week to improve Clopad's error feedback, I strongly suggest you pull and rebuild.

**Comment by ILoveHubGit** [comment]
Thanks for your response
