### ISSUE TITLE
Cannot split window horizontally

### ISSUE THREAD

**Issue by chilip3pp3r** [fredoverflow/clopad#5]
Wonderfully simple clojure editor! How to split the window horizontally (as in your YouTube demos) instead of vertically, which appears to be the default on launch?

Right-clicking does not bring up a context menu.

**Comment by chilip3pp3r** [comment]
Hmm, interesting … I see the "horizontal split” commit from November 3 (2022). I can't seem to manipulate the location of the panes with my mouse or a context menu.

I am on macOS Monterey.

**Comment by fredoverflow** [comment]
I consider the old layout inferior to the new one, but it is still maintained on its own branch, at least for now:

    cd clopad
    git checkout classic
    mvn package

**Comment by chilip3pp3r** [comment]
Thank you. I really enjoyed your Clojure Advent of Code. Wonderful demonstration of the language.

I will leave a breadcrumb to it here for future readers: https://youtube.com/playlist?list=PLbPrugU2oQ8VURsQdZ6W_iovXRS24UmZQ

**Comment by fredoverflow** [comment]
Thanks! I solved last year in Clojure as well, albeit off-camera: https://github.com/fredoverflow/advent

**Comment by ptrgyd** [comment]
Wonderful. (“Very cool.” ;-)

 Please consider allowing YouTube to automatically provide (non-German)
captions for your German language channel. You have deep expertise and
provide great instruction. Bravo.

**Comment by ptrgyd** [comment]
Auto-translate is available for your videos!

In the (Android) YouTube app while watching a video:

Top-right settings gear > Captions > Auto-translate > [Select language]
